
package View.GUI;

import javax.swing.JPanel;
import deepspace.DamageToUI;

/**
 * @brief Esta clase implementa la interfaz gráfica de un objeto de tipo Damage.
 * Puede instanciar tanto objetos de tipo Numeric como de tipo Specific
 */
public class DamageView extends JPanel {

    /**
     * Constructor por defecto de la clase
     */
    public DamageView() {
        initComponents();
    }
    
    /**
     * @brief Asocia al panel un objeto ToUI de Damage
     * @param damage : Objeto DamageToUI que se pasará a la vista
     */
    void setDamage(DamageToUI damage){
        if(damage == null){
            setVisible(false);
        }
        else{
            weapons.setText(damage.getWeaponInfo());
            shields.setText(Integer.toString(damage.getNShields()));
            repaint();
            revalidate();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleWeapons = new javax.swing.JLabel();
        titleShields = new javax.swing.JLabel();
        shields = new javax.swing.JLabel();
        weapons = new javax.swing.JTextArea();

        setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Pérdidas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12))); // NOI18N
        setPreferredSize(new java.awt.Dimension(399, 124));

        titleWeapons.setFont(new java.awt.Font("Ubuntu", 1, 13)); // NOI18N
        titleWeapons.setText("Armas :");

        titleShields.setFont(new java.awt.Font("Ubuntu", 1, 13)); // NOI18N
        titleShields.setText("Escudos :");

        shields.setFont(new java.awt.Font("Ubuntu", 1, 13)); // NOI18N
        shields.setText("jLabel2");

        weapons.setEditable(false);
        weapons.setBackground(new java.awt.Color(239, 239, 239));
        weapons.setColumns(20);
        weapons.setFont(new java.awt.Font("Ubuntu", 1, 13)); // NOI18N
        weapons.setLineWrap(true);
        weapons.setRows(5);
        weapons.setBorder(null);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(titleWeapons)
                        .addGap(18, 18, 18)
                        .addComponent(weapons))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(titleShields)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(shields)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titleShields)
                    .addComponent(shields))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(titleWeapons)
                        .addGap(0, 53, Short.MAX_VALUE))
                    .addComponent(weapons, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel shields;
    private javax.swing.JLabel titleShields;
    private javax.swing.JLabel titleWeapons;
    private javax.swing.JTextArea weapons;
    // End of variables declaration//GEN-END:variables
}
