
package View.GUI;
import controller.Controller;
import javax.swing.JPanel;
import deepspace.EnemyToUI;
import deepspace.GameState;


/**
 * @brief Esta clase implementa la interfaz gráfica de un objeto de tipo EnemyToUI
 */
public class EnemyStarShipView extends JPanel {
    private LootView lootView;
    private DamageView damageView;
    
    /**
     * Constructor por defecto de la clase
     */
    public EnemyStarShipView() {
        initComponents();
        
        lootView = new LootView();
        enemyLootPanel.add(lootView);
        
        damageView = new DamageView();
        enemyDamagePanel.add(damageView);
        
        
    }
    
    /**
     * @brief Asocia al panel un objeto ToUI de EnemyStarShip
     * @param e : Objeto EnemyToUI que se le pasará a la vista
     */
    void setEnemy(EnemyToUI e){
        enemyName.setText(e.getName());
        enemyFire.setText(Float.toString(e.getAmmoPower()));
        enemyShield.setText(Float.toString(e.getShieldPower()));
        
        lootView.setLoot(e.getLoot());
        damageView.setDamage(e.getDamage());
        
        if(Controller.getInstance().getState() == GameState.BEFORECOMBAT || Controller.getInstance().getState() == GameState.INIT){
            lootView.setVisible(false);
            damageView.setVisible(false);
        }
        else{
            lootView.setVisible(true);
            damageView.setVisible(true);
        }
        
        repaint();
        revalidate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        enemyTitle = new javax.swing.JLabel();
        fireTitle = new javax.swing.JLabel();
        shieldTitle = new javax.swing.JLabel();
        enemyLootPanel = new javax.swing.JPanel();
        enemyDamagePanel = new javax.swing.JPanel();
        enemyName = new javax.swing.JLabel();
        enemyFire = new javax.swing.JLabel();
        enemyShield = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        enemyTitle.setFont(new java.awt.Font("Ubuntu", 1, 13)); // NOI18N
        enemyTitle.setText("Enemigo:");

        fireTitle.setFont(new java.awt.Font("Ubuntu", 1, 13)); // NOI18N
        fireTitle.setText("Potencia de fuego:");

        shieldTitle.setFont(new java.awt.Font("Ubuntu", 1, 13)); // NOI18N
        shieldTitle.setText("Potencia de defensa:");

        enemyLootPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        enemyDamagePanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        enemyName.setFont(new java.awt.Font("Ubuntu", 1, 13)); // NOI18N
        enemyName.setText("jLabel1");

        enemyFire.setFont(new java.awt.Font("Ubuntu", 1, 13)); // NOI18N
        enemyFire.setText("jLabel1");

        enemyShield.setFont(new java.awt.Font("Ubuntu", 1, 13)); // NOI18N
        enemyShield.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(enemyTitle)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(enemyName))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(fireTitle)
                                    .addComponent(shieldTitle))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(enemyShield)
                                    .addComponent(enemyFire)))
                            .addComponent(enemyLootPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(enemyDamagePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(enemyTitle)
                    .addComponent(enemyName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fireTitle)
                    .addComponent(enemyFire))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(shieldTitle)
                    .addComponent(enemyShield))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(enemyLootPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(enemyDamagePanel, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel enemyDamagePanel;
    private javax.swing.JLabel enemyFire;
    private javax.swing.JPanel enemyLootPanel;
    private javax.swing.JLabel enemyName;
    private javax.swing.JLabel enemyShield;
    private javax.swing.JLabel enemyTitle;
    private javax.swing.JLabel fireTitle;
    private javax.swing.JLabel shieldTitle;
    // End of variables declaration//GEN-END:variables
}
