
package View.GUI;

import javax.swing.JPanel;
import deepspace.ShieldToUI;

/**
 * @brief Esta clase implementa la interfaz gráfica de un objeto de tipo ShieldToUI
 */
public class ShieldView extends JPanel implements CombatElementView{
    
    private boolean selected = false;

    /**
     * Constructor por defecto de la clase
     */
    public ShieldView() {
        initComponents();
        setOpaque(selected);
    }
    
    /**
     * @brief Determina si el objeto está seleccionado por el usuario
     * @return selected
     */
    @Override
    public boolean isSelected () {
        return selected;
    }
    
    /**
     * @brief Asocia al panel un objeto ToUI de ShieldView
     * @param shield : Objeto ShieldToUI que se le pasará a la vista
     */
    void setShield(ShieldToUI shield){
        power.setText(Float.toString(shield.getBoost()));
        uses.setText(Integer.toString(shield.getUses()));
        revalidate();
        repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titlePotencia = new javax.swing.JLabel();
        titleUsos = new javax.swing.JLabel();
        power = new javax.swing.JLabel();
        uses = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 102));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        titlePotencia.setFont(new java.awt.Font("Ubuntu", 1, 13)); // NOI18N
        titlePotencia.setText("Potencia :");

        titleUsos.setFont(new java.awt.Font("Ubuntu", 1, 13)); // NOI18N
        titleUsos.setText("Usos :");

        power.setFont(new java.awt.Font("Ubuntu", 1, 13)); // NOI18N
        power.setText("jLabel1");

        uses.setFont(new java.awt.Font("Ubuntu", 1, 13)); // NOI18N
        uses.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(titlePotencia)
                    .addComponent(titleUsos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(uses)
                    .addComponent(power))
                .addGap(27, 27, 27))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titlePotencia)
                    .addComponent(power))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titleUsos)
                    .addComponent(uses))
                .addContainerGap(22, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        selected = !selected;
        setOpaque (selected);
        repaint();
    }//GEN-LAST:event_formMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel power;
    private javax.swing.JLabel titlePotencia;
    private javax.swing.JLabel titleUsos;
    private javax.swing.JLabel uses;
    // End of variables declaration//GEN-END:variables
}
